New Updates (#9)
* Get more things working

* Create dependabot.yml

* Fix workflow

* Remove dependabot for NPM packages Node is not running in production

* Remove gulp add from workflow

* Fix bugs

* Test

* Test

* Supply DB URL instead

* Add database ready script

* Add bash

* Add bash

* Add bash

* Add bash

* Load vars at php startup

* test

* test

* test

* Fix build

* Test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,6 +41,11 @@ jobs:
       #       --ignore-dirty \
       #       --no-interaction \
       #       --verbose
+      # Uncomment to build a docker image.
+      # - name: Build and push docker image
+      #   run: |
+      #   docker build -t registry.k3s.rocksthe.net/drupal-rk1:latest -f ./Dockerfile /tmp/blt-deploy
+      #   docker push registry.k3s.rocksthe.net/drupal-rk1:latest
 
   # Uncomment for SonarQube analysis
   # sonarscan:
@@ -75,8 +80,6 @@ jobs:
       image: mobomo/drupalstand-ci:8.2-ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - name: Globally install gulp-cli
-        run: npm install --global gulp-cli
       - name: Install dependencies
         run: |
           composer install --no-interaction --no-progress
@@ -118,7 +121,6 @@ jobs:
         DRUPAL_DB_HOST: mariadb
         DRUPAL_DB_PORT: 3306
         DRUPAL_CONFIG_DIR: /app/config
-        PHP_IDE_CONFIG: "serverName=appserver"
         ENVIRONMENT: ci
     steps:
       - uses: actions/checkout@v4
@@ -126,12 +128,31 @@ jobs:
         run: |
           composer install --no-interaction --no-progress
           # npm install --prefix webroot/themes/contrib/uswds_base
+      - name: Wait for MySQL Ready
+        shell: bash
+        run: |
+          failcounter=0
+          timeout_in_sec=120
+
+          until mysql -h $DRUPAL_DB_HOST -u $DRUPAL_DB_NAME -p$DRUPAL_DB_PASS -D $DRUPAL_DB_NAME --silent -e "show databases;"
+          do
+            let "failcounter += 1"
+            echo "Waiting for database connection... ($failcounter/$timeout_in_sec)"
+            if [[ $failcounter -gt timeout_in_sec ]]; then
+              echo "Timeout ($timeout_in_sec seconds) reached; failed to connect to database"
+              exit 1
+            fi
+            sleep 2
+          done
       - name: Initialize Drupal + Verify Config can import
         run: |
+          # For some reason drush locks to "127.0.0.1" if this is set.
+          unset CI
+
           echo "memory_limit = 768M" >> /etc/php/8.2/cli/conf.d/my-php.ini
-          ./vendor/bin/drush site:install minimal --yes --account-name=admin --account-pass=admin install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
+          ./vendor/bin/drush site:install minimal --yes --account-name=admin --account-pass=admin --db-url="mysql://$DRUPAL_DB_USER:$DRUPAL_DB_PASS@$DRUPAL_DB_HOST:$DRUPAL_DB_PORT/$DRUPAL_DB_NAME" -vvv install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
           
-          if [ -d "./config/default" ]; then
+          if [ -f "./config/default/system.site.yml" ]; then
             cat ./config/default/system.site.yml | grep uuid | tail -c +7 | head -c 36 | ./vendor/bin/drush config-set -y system.site uuid -
             ./vendor/bin/drush config:import --yes || true
             ./vendor/bin/drush config:import --yes || true
